/** Shapes returned by the VoidCat Workers API (see api/src/routes). */

export interface Grant {
  id: string;
  title: string;
  agency: string | null;
  agency_code?: string | null;
  program?: string | null;
  description?: string | null;

  /** Pre-formatted display string, e.g. "$250,000". */
  amount?: string | null;
  award_floor?: number | null;
  award_ceiling?: number | null;
  estimated_funding?: number | null;

  deadline?: string | null;
  close_date?: string | null;
  post_date?: string | null;

  opportunity_number?: string | null;
  opportunity_type?: string | null;
  cfda_number?: string | null;
  eligibility?: string | null;

  applicant_types?: string[];
  funding_categories?: string[];
  tags?: string[];
  keywords?: string[];

  matching_score?: number;
  data_source?: string | null;
  last_verified?: string | null;
}

export interface GrantSearchResponse {
  success: true;
  count: number;
  grants: Grant[];
  data_source: string;
  execution_type: string;
  timestamp: string;
}

export interface User {
  id: string | number;
  email: string;
  name: string;
  company?: string | null;
  subscription_tier: string;
  created_at?: string;
}

export interface AuthTokens {
  access_token: string;
  refresh_token?: string;
  token_type?: string;
  expires_in?: number;
  expires_at?: string;
}

export interface AuthResponse extends AuthTokens {
  success: true;
  message: string;
  user: User;
}

export interface CompanyProfile {
  name: string;
  description: string;
  expertise?: string;
}

export interface ProposalSections {
  executive_summary: string;
  technical_approach: string;
  commercial_potential: string;
  budget_summary?: {
    personnel: number;
    equipment: number;
    overhead: number;
    total: number;
  };
  timeline?: { phase: string; task: string }[];
}

export interface ProposalResponse {
  success: true;
  proposal: ProposalSections;
  /** "real" when generated by a live model; "template" only in development. */
  execution_type: string;
  ai_enhanced: boolean;
  grant_details: { id: string; title: string; agency: string };
  generated_at: string;
}
